### ISSUE TITLE
VELIS EVO WI-FI

### ISSUE THREAD

**Issue by HALDigital** [julupanter/homeassistant-ariston-sensor#3]
Hi,

I have a Ariston Velis Evo Wi-Fi hot water storage heater, which is connected to the internet and can be controlled with an app. The device also shows up on https://www.ariston-net.remotethermo.com/ but there I can only check the error log and not change any settings or check the temperature like in the app.

I'd like to log the water temperature and found your script. The login works, but when it should get the actual data, after logging in, the response is "Failed reading DhwTimeProg: :-( EverywareCloud error from F0AD3E02E27D (Http status: 401 - Unauthorized)"

But I'm sure I'm logged in successfully, because I get the token and connectionid - if I try with wrong credentials, it fails right at the start.

Do you have an idea what the problem is? Maybe this water storage heater can't be queried this way?
How did you do it? What documentation did you use? Where did you find it? Or did you reverse engineer something?

Any help is much appreciated.

UPDATE: My App stopped working. I guess I've been blocked. Maybe because of too many tests with wrong credentials. Changing my IP does not help. Let's wait a day and see what happens.

2nd UPDATE: The App on the Smartphone works again, but I can't get my script to work. Either I get a gateway timeout or just "" as a response, depending if I use the serial number or the plant id in the script.

FINAL UPDATE: I was able to get it working with https://pypi.org/project/aristonremotethermo/1.0.17/
As suspected the communication for Velis products is different.

**Comment by doctorvanmartin** [comment]
Sorry for the loooong delay.

For velys use this very good one, https://github.com/chomupashchuk/ariston-aqua-remotethermo-home-assistant
